export { default as UserLogin } from './login'
export { default as UserRegister } from './register'
export { default as UserAccount } from './account'
export { default as UserOnboarding } from './onboarding'
export { default as UserDashboard } from './dashboard'
